spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/database
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

